{% set version = "v0.3.0" %}
{% set checksum = "825a11fad400146109bfd996ce88a46248499a9a22a01e1633283a0f97e2c87c" %}

package:
    name: inferno
    version: {{ version }}

source:
    url: https://github.com/inferno-pytorch/inferno/archive/{{ version }}.tar.gz
    sha256: {{ checksum }}

build:
    number: 1000
    script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
    noarch: python

requirements:
    host:
        - python >=3.6
        - pip
        - pytest-runner

    run:
        - python >=3.6
        - pyyaml
        - scipy
        - scikit-image
        - h5py
        - dill
        - networkx 1.11
        - tensorboardx >=1.4
        - pytorch >=0.3,<1.1
        - torchvision >=0.2,<0.3

test:
    imports:
        - inferno

about:
    license: Apache 2.0
    license_file: LICENSE
    license_family: APACHE
    summary: A utility library around PyTorch
    home: https://github.com/inferno-pytorch/inferno

extra:
    recipe-maintainers:
        - constantinpape
        - nasimrahaman
