{% set version = "v0.3.2" %}
{% set checksum = "8c347eca43eb4d61515889c0b2f4bc5c0bb3eeddec31171b490d3cc986ecfcd7" %}

package:
    name: inferno
    version: {{ version }}

source:
    url: https://github.com/inferno-pytorch/inferno/archive/{{ version }}.tar.gz
    sha256: {{ checksum }}

build:
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
    noarch: python

requirements:
    host:
        - python >=3.6
        - pip
        - pytest-runner

    run:
        - python >=3.6
        - pyyaml
        - scipy
        - scikit-image
        - h5py
        - dill
        - networkx
        - tensorboardx >=1.4
        - pytorch >=0.3,<1.2
        - torchvision >=0.2,<0.3

# test:
#     imports:
#         - inferno

about:
    license: Apache 2.0
    license_file: LICENSE
    license_family: APACHE
    summary: A utility library around PyTorch
    home: https://github.com/inferno-pytorch/inferno

extra:
    recipe-maintainers:
        - constantinpape
        - nasimrahaman
