{% set version = "v0.4.0" %}
{% set checksum = "550a183cf84b6f0ad1a883e25d4852a713c5fe5403fb9b4fee54246084424a9c" %}

package:
    name: inferno
    version: {{ version }}

source:
    url: https://github.com/inferno-pytorch/inferno/archive/{{ version }}.tar.gz
    sha256: {{ checksum }}

build:
    number: 1
    script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
    noarch: python

requirements:
    host:
        - python >=3.6
        - pip
        - pytest-runner

    run:
        - python >=3.6
        - pyyaml
        - scipy
        - scikit-image
        - h5py
        - dill
        - networkx
        - tensorboardx >=1.4
        - pytorch >=0.4,<2.0
        - torchvision >=0.2,<1.0

test:
    imports:
        - inferno

about:
    license: Apache 2.0
    license_file: LICENSE
    license_family: APACHE
    summary: A utility library around PyTorch
    home: https://github.com/inferno-pytorch/inferno

extra:
    recipe-maintainers:
        - constantinpape
        - nasimrahaman
