appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ayGggTTXxcGY8yfG6klxqdZgfwWdrdGvnUbOCzX9EdAWSbQ7NqB6+5tm2syEZFzZFHhFvOoFa3FY/ZlRLTKBXKfO9cBMKvdT9z70bL0xaGeP+D2wnSQDKoxwEFcEwCzssBndxazurYJnR3yDGReSPpCVT9+qzLEz8MhTtekfE4B/hfSbvZtELdoyvItVc8FpUywJ/ikDHll4rWRZkGHkftjG/jTX+j9ReRHaERcxqWaznw+RFobInV2eZ4tkBHSGP1zqxrTfYpTJdAJkYwcsRLH2uCRVNQ1SFykVW2Af886k7N6XFNbGKVy/pYdHpjdmaF5Fm7vQTm1A1lkUX/AOTKTWUHfwnL0JGvGnAIid/n5lEOMwj1pkb9XnXHEry/Qgj36BrkBqjkFmsimCtgQPFCcUzIh/5eTA9IVfy/dwgbztZgZqfBu6VaAbCwgRflmtUkTRjjuS7rXzJ0p5T+bSq/8V21UHXn0+X9Qv3hGYjLa7W1l4/3RDk/OXk3Hn+5LRv1y3OlB2aH9xENpURBfD7aWWXst79WCyyIgbdqIBSPLSOlswINknhDF3M3Sno+Sfu9sHZXmrFQFYNbdH2KXcW/Uxv21jhh7aab2J29DtvaGnCcqHXO4DvH7jCVIH5A+FFI2pIchuDvRRvnhfILrKctLGC/sxrjLYllNeZrmOlb8=}
